project:
  type: website
  output-dir: docs

website:
  title: "Sandeep Sharma"
  navbar:
    right:
      - text: "Blog"
        href: blog.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Projects"
        href: projects.qmd
      - about.qmd
      - icon: github
        href: https://github.com/imsndp10
      - icon: twitter
        href: https://twitter.com
      - icon: Linkedin
        href: https://www.linkedin.com/in/sandeepsharma2016/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

