project:
  type: website
  output-dir: docs

website:
  title: "Sandeep Sharma"
  navbar:
    right:
      - text: "Blog"
        href: blog.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Projects"
        href: projects.qmd
      - about.qmd
      - icon: github
        href: https://github.com/imsndp10
      - icon: twitter
        href: https://twitter.com
      - icon: Linkedin
        href: https://www.linkedin.com/in/sandeepsharma2016/
format:
  html:
    theme: lux
    css: styles.css
    include-in-header: 
      - text: '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">'

editor: visual

